apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mmbot
  description: A bot for Make Monmouth
  annotations:
    github.com/project-slug: 'makemonmouth/mmbot'
    grafana/tag-selector: mmbot
    sentry.io/project-slug: mmbot
    backstage.io/techdocs-ref: dir:docs/
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
    prometheus.io/alert: all
spec:
  type: service
  owner: matt@doics.co
  lifecycle: production
  dependsOn: 
    - Resource:default/MVentory
  consumesApis:
    - mventory-api
