apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mmbot
  description: A bot for Make Monmouth
  annotations:
    github.com/project-slug: 'makemonmouth/mmbot'
    grafana/tag-selector: "mmbot"
    prometheus.io/alert: "ConsulUp"
spec:
  type: service
  owner: matt@doics.co
  lifecycle: production
  dependsOn: 
    - Resource:default/MVentory
  consumesApis:
    - mventory-api
