apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mmbot
  description: A bot for Make Monmouth
  # Example for optional annotations
  annotations:
    github.com/project-slug: makemonmouth/mmbot
spec:
  type: bot
  owner: matt@doics.co
  lifecycle: production
